### ISSUE TITLE
Support inline references for script packages

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#156]
It would be great to support inline load of a package like https://www.nuget.org/packages/simple-targets-csx/. 
It's a CSX package so it contains script files that should be `#loaded`.

**Comment by adamralph** [comment]
😍 Coincidentally, I started playing with using dotnet-script to execute simple-targets-csx build script this morning. This feature would make that an even more compelling use case.

**Comment by filipw** [comment]
I think there is a philosophical discussion needed here, is this a `#load` or is this an `#r`? 😂

**Comment by adamralph** [comment]
It's neither. It's a package reference. I'm sceptical whether #r was the
right choice for NuGet packages, but if that's how it is, then #r is the
right choice. A package could even have both assemblies and scripts.

**Comment by seesharper** [comment]
I think introducing a new directive requires a lot more work than relying on existing directives such as `#load` and `#r`.  If I am not mistaken it would require changes in Roslyn to make it not complain about an unknown directive. 

The fact that we use the `#r` directive for multiple purposes sort of aligns with how we see dependencies displayed in full Visual Studio where we have Dependencies as the top level node and then we have assembly references and NuGet references below that. 

I do agree that we should use the `#r` directive here since it is actually a NuGet package and it should be relatively easy to include csx files found in the package. It would make for a great feature for dotnet-script

**Comment by seesharper** [comment]
@adamralph @filipw 

I took a quick look at this and it is probably not so easy to do, but let's review our options here.

**Custom SourceResolver**

We could implement this as a custom `SourceResolver ` and provide syntax like this 

```
#load "nuget: simple-targets-csx, 5.3.0"
```

The problem here is that the `SourceResolver` is expected to return a `Stream` that points to a single file representing the resolved file. The package can contain multiple files and there is no way of knowing which is the "entry point" We could of course create syntax for specifying this like 

```
#load "nuget: simple-targets-csx/simple-targets.csx, 5.3.0"
```

that allows us to be explicit with regards to which file from the package we actually want to load.

**Combine `#r` and `#load`**

This approach splits the resolving of the NuGet package and the loading of the script into two operations.

```
#r "nuget:simple-targets-csx, 5.3.0"
#load "simple-targets.csx"
```

We would still have to implement a custom `SourceResolver` that wraps/decorates the underlying `SourceResolver` so that we can resolve the `#load` directive and load the script file from where the package gets installed which would be the global NuGet cache.

**Comment by adamralph** [comment]
> I think introducing a new directive requires a lot more work than relying on existing directives such as #load and #r. If I am not mistaken it would require changes in Roslyn to make it not complain about an unknown directive.

Correct, but that doesn't mean a new directive isn't (or wasn't) the better solution, and it could have been built into Roslyn some time ago. Anyway, it's probably not worth pursuing that thread much longer here. For one reason or another `#r` ended up as the directive supporting NuGet and we may as well operate under the assumption that this isn't going to change,

So, leaving that aside:

I'm not sure it's best to invent a new scheme for csx files specifically. It may be best to align with the current NuGet convention of `contentFiles/{language}/{TFM}` for content files and include (equivalent of `#load`) anything matching `contentFiles/csx/any/*.csx` (where `any` could also be any TFM compatible with the runtime executing dotnet-script) in our script compilation.

Whether or not `#r` should be used depends on its semantics. Is it an assembly reference, or is it a package reference? If we compare it with new SDK-style csproj, `#r` was originally the equivalent of the `Reference` element, e.g.

```xml
<Reference Include="Foo">
  <HintPath>Foo.dll</HintPath>
</Reference>
```

But since the addition of the NuGet prefix, `#r` is now more the equivalent of the `PackageReference` element, and indeed, the NuGet package is now largely the "standard" unit of reference. The `PackageReference` element already supports content files and it includes files matching, e.g. `contentFiles/cs/any/*.cs` in the project compilation targets. It would seem natural for the scripting package reference, `#r`, to support csx files in the same manner.

Also consider a NuGet package which has assemblies in `lib/` _and_ C# files in `contentFiles/cs/{TFM}`. I haven't tested it, but I assume that the csproj `PackageReference` element honours the existence of both artifacts, and add references to the assemblies as well as including the content files in the compilation targets. I imagine we'd want to do the equivalent for a NuGet package containing both assemblies and C# scripts in `content/csx/{TFM}`, i.e. add references to the assemblies and include the csx files in our script compilation.

**Comment by seesharper** [comment]
@adamralph @filipw 

Did a spike on this and have the following working now

Script 
```
#r "nuget:simple-targets-csx, 5.3.0"
#load "simple-targets.csx"

using static SimpleTargets;

var targets = new TargetDictionary();

targets.Add("default", () => Console.WriteLine("Hello, world!"));

Run(Args, targets);
```

Result 
```
simple-targets: Running "default"...
simple-targets/default: Starting...
Hello, world!
simple-targets/default: Succeeded.
simple-targets: "default" succeeded.
```

**Comment by seesharper** [comment]
This actually require very little work on our part since most of it is already implemented in Roslyn. The `SourceReferenceResolver` takes an array of search paths where we can pass the path to the source package location on disk. We just need to determine if it is a source package which does not have to be more advanced than looking to see if it contains any csx files.

**Comment by seesharper** [comment]
For reference, this is the csproj file generated behind the scenes by `dotnet.script.dependencymodel`

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="simple-targets-csx" Version="5.3.0" />
  </ItemGroup>
</Project>
```

`dotnet restore` does not really do anything besides resolving the package and install it into the global NuGet cache. 


> Also consider a NuGet package which has assemblies in lib/ and C# files in contentFiles/cs/{TFM}. I haven't tested it, but I assume that the csproj PackageReference element honours the existence of both artifacts, and add references to the assemblies as well as including the content files in the compilation targets. I imagine we'd want to do the equivalent for a NuGet package containing both assemblies and C# scripts in content/csx/{TFM}, i.e. add references to the assemblies and include the csx files in our script compilation.

"Content Files" are no longer automatically honored in the sense that they will not be included as an compilation asset into the project.

https://github.com/NuGet/Home/issues/4803

There are however traces of the `project.assets.json` file that is the result of `dotnet restore` 

```
    "simple-targets-csx/5.3.0": {
      "sha512": "ItflkoSzoNgVZE8ckBnNJElVgoxcPUx3tHo0mcKDm5Co5FaDloCcjJE8hp7xEYOzZD6cuaY1nqtBg2QFd2jJpg==",
      "type": "package",
      "path": "simple-targets-csx/5.3.0",
      "files": [
        "internal/runner.csx",
        "internal/target-runner.csx",
        "internal/util.csx",
        "simple-targets-csx.5.3.0.nupkg.sha512",
        "simple-targets-csx.nuspec",
        "simple-targets-target.csx",
        "simple-targets.csx"
      ]
    }
```

Anyhow, that is not all that important in this context. We can resolve script files included in packages and your package, @adamralph  worked right out of the box. 👍

**Comment by adamralph** [comment]
A separate `#r` and `#load` doesn't work for me. Imagine:

```csx
#r "nuget:Foo, 1.0.0"
#r "nuget:Bar, 1.0.0"
#load "util.csx"
```

Where both Foo and Bar contain a util.csx.

> We just need to determine if it is a source package...

What is a "source package"? What is a package that contain both csx and dll?

**Comment by adamralph** [comment]
> "Content Files" are no longer automatically honored in the sense that they will not be included as an compilation asset into the project.

That is not true. Content files do currently work with `PackageReference`. The issue you linked has been closed and moved. See https://github.com/dotnet/sdk/issues/1100#issuecomment-336733893

**Comment by seesharper** [comment]
> That is not true. Content files do currently work with PackageReference. The issue you linked has been closed and moved. See dotnet/sdk#1100 (comment)

Great. I did not know that 

To remove the chance of ambiguity could we do this?

```
#r "nuget:Foo, 1.0.0"
#r "nuget:Bar, 1.0.0"
#load "Foo/util.csx"
```

**Comment by adamralph** [comment]
`#load "Foo/util.csx"`

How do we know whether "Foo" is a NuGet package or a folder? What if it's both? I'm not seeing the advantage of the separate `#load`

**Comment by seesharper** [comment]
The chance of both should be rather small, don’t you think?
The load is needed to actually load the script. I don’t think we can programmatically add references to csx files like we do with metadata references.

What is your suggestion then given the cards on the table?

**Comment by adamralph** [comment]
The _chance_ isn't really the point. It's counter-intuitive:

```csx
#r "nuget:Bar, 1.0.0"

#load "Foo/util.csx"
#load "Bar/util.csx" // watch out! The others are folders but this one isn't.
#load "Baz/util.csx"
```

Also where would these files live in the NuGet package? In the root? What if I want to include assemblies or executables as well? Do I have some artifacts in the root (csx) and others under lib (assemblies) or tools (executables)?

Let's use existing NuGet conventions instead.

My suggestion is as [above](https://github.com/filipw/dotnet-script/issues/156#issuecomment-340901094): use the existing NuGet convention for content files. Include any scripts found matching `contentFiles/csx/{compatible TFMs}/*.csx` in the compilation.

**Comment by seesharper** [comment]
Clearly I don’t have all the answers to all scenarios yet. I started thinking about this a few hours ago:) but just for reference, could you show me the complete script as you would like it to be.

**Comment by adamralph** [comment]
@seesharper I'd like the script to look exactly like [yours](https://github.com/filipw/dotnet-script/issues/156#issuecomment-340901558), minus the `#load` line.

Your suggestion of `#load "nuget: simple-targets-csx, 5.3.0"` is also a viable alternative. In this way, `#r` remains the "assembly reference" directive, and `#load` expands it's responsibility as the "script loading" directive, by becoming Nuget-enabled. Under my suggestion of using the current conventions for Nuget package internals, there is a nice symmetry, since `#r` references all assemblies that match `lib/{compatible TFMs}/*.dll` and `#load` would compiles all scripts that match `contentFiles/csx/{compatible TFMs}/*.csx`.

> The problem here is that the `SourceResolver` is expected to return a `Stream` that points to a single file representing the resolved file. The package can contain multiple files and there is no way of knowing which is the "entry point" We could of course create syntax for specifying this like

I assume that the `Stream` could be constructed so that it returns the contents of each file in sequence? But more generally, if there are technical limitations then it's probably time to talk to the Roslyn team to see what can be done in the scripting libs before discounting the solution. More generally still, this entire feature should eventually be built into the Rosyln scripting libs (as should the current `#r` for NuGet packages, if not already done). I realise it may take time for those things to happen, but I believe it's best that any work done in a specific runner to support these things in the meantime should be regarded as poly-fill for the eventual support in the scripting libs, so it would be best to have the Roslyn team involved in the conversation around the design of the API.

**Comment by seesharper** [comment]
First of all i would like to emphasize that we are not trying to create the IE6 of scripting here.  Our intent is to push C# scripting forward while trying hard to adhere to whatever we have with regards to standards (or lack of it ). We talked to the Roslyn team when discussing how the `#r`syntax should be when referencing NuGet packages. We actually had `#r nuget:package/version` to begin with. 
A tremendous amount of work have been put into making this work across the whole stack from the runner all the way to OmniSharp.Roslyn providing compilation metadata.

Okay, back to business here.

```
#r "nuget:Foo, 1.2.3"
#r "nuget:Bar, 1.2.3
```

That was what I initially thought it would look like and I will investigate further if there is a possibility to load the scripts without a `#load` directive. 
How do we deal with ambiguity here ? Both packages can contain `ùtils.csx` as you mentioned before.


```
#load "nuget: Foo, 1.2.3"
#load "nuget: Bar 1.2.3"
```

Should be possible to implement, but probably same problem with regards to ambiguity?

**Comment by filipw** [comment]
How about if `#load "nuget: Foo, 1.2.3"` resolved the nuget package, discovered *all* CSX paths in that nuget and generated a temporary file containing `#load` directives to all the files i.e.
```
#load  "<nuget_package_location>/internal/runner.csx",
#load  "<nuget_package_location>/internal/target-runner.csx",
#load  "<nuget_package_location>/internal/util.csx",
#load  "<nuget_package_location>/simple-targets-target.csx",
#load  "<nuget_package_location>/simple-targets.csx"
```
and returned *that* file as the resolved `Stream` to Roslyn? Then everything else should just fall into place.

The issue is of course you don't know which file is the "entry point" but I don't think it matters, if you reference the entire package with multiple files, then it's a fair assumption you want all of the files from there.

**Comment by adamralph** [comment]
@filipw that's the kind of thing I had in mind, but perhaps it's worth investigating the creation of a `MultiFileStream` type that stitches the files together without the need to write out a temporary file (perhaps such a thing already exists somewhere). Or alternatively, could we create a string containing the load statements for all files, and return it via a `MemoryStream`? I agree that all csx files should be loaded (while respecting the content files folder conventions).

@seesharper it's good to hear that the aim is to develop and adhere to standards. Does that mean that the Roslyn team will be brought into the conversation before this is implemented?

It sounds like we are homing in on either `#r "nuget:Foo, 1.2.3"` or `#load "nuget:Foo, 1.2.3"`. Which one doesn't really make a difference apart from one case: when a nupkg contains both assemblies and script files. Do we want both to be used from a single `#r` or do we want separate `#r` and `#load`? While the latter gives more flexibility, it's more verbose, and somewhat diverges from the concept of a NuGet package as the atomic unit of reference, which is expressed in MSBuild by the `PackageReference` element, which wraps assembly referencing, content file inclusion, build targets and props inclusion, etc. It would be interesting to hear the Roslyn's team opinion on this.

**Comment by seesharper** [comment]
@filipw That is not a bad idea at all. In fact when I think about it we do something similar at work where we have a `common.csx` file that `#load`'s a bunch of other csx files.  Sort of a meta script file :)

When we talk about ambiguity and the chance of collision either on script file name or classes defined in those files, there is always a chance for this to happen. There are for instance no namespaces in script files so the chance increases rapidly just because of that. 

In my opinion, it would be best to make a clear distinction between regular NuGet packages (packages containing assemblies) and "script" packages containing csx files. If your script package has binary dependencies it could just bring them in using the already supported `#r nuget....` syntax.

**Comment by adamralph** [comment]
A "regular" NuGet package already provides for the shipping of assemblies, content files, and build files all in one package, and everything just works. I'm not sure it's wise to carve off packages containing csx files into a special category of their own.

**Comment by seesharper** [comment]
Not a problem really. We add the package as a PackageReference anyway so we will support this out of the box. 

But I think we both can agree that the 95% case here is that such a package contains only csx files and therefore it makes sense to use the `#load nuget:Foo, 123` syntax where we load both assemblies and csx files?

**Comment by adamralph** [comment]
That means that as soon as a nuget package adds csx files, you have to switch from `#r` to `#load` to get them. It doesn't feel right to me. I believe it should be either:

- `#r` does everything, or
- `#r` references assemblies and `#load` compiles scripts

**Comment by adamralph** [comment]
Again, this is why I believe `#r` probably shouldn't have been used for referencing assemblies in NuGet packages. It would be cleaner to have a new "package reference" directive, e.g. `#p`, with everything it does driven by NuGet conventions.

```csx
#p "mypackage, 1.0.0" // equivalent of <PackageReference>
#r "assemblynameorpath" // equivalent of <Reference>
#load "script.csx"  // no equivalent - script specific
```

Assuming that isn't feasible, we're left with:

```csx
#r "nuget:mypackage, 1.0.0" // equivalent of <PackageReference>
#r "assemblynameorpath" // equivalent of <Reference>
#load "script.csx"  // no equivalent - script specific
```

So effectively, `#r "nuget:{name}, {version}"` is an alias for `#p "{name}, {version}"`. I think that's better than:

```csx
#r "nuget:mypackage, 1.0.0" // only references the assemblies, no equivalent - script specific
#r "assemblynameorpath" // equivalent of <Reference>
#load "nuget:mypackage, 1.0.0" // only compiles the scripts, no equivalent - script specific
#load "script.csx"  // no equivalent - script specific
```

A variant where `#load "nuget:..."` both references assemblies and compiles scripts is worse still.

**Comment by filipw** [comment]
I think - given also the current limitations and extensibility points in Roslyn - it's not crazy to use `#r` for one scenario and `#load` for the other scenario. 

At the moment, in the compiler, `#r` stands for a `MetadataReference`, which we just extended to resolve more `MetadataReferences` from a nuget package.
Similarly, in the compiler, `#load` stands for an extra source file to be used, which similarly could be extended to resolve more source files from a nuget package.

This to me sounds rather reasonable.

Now, like with everything, there are edge cases here but in order to address them a considerable change on how Roslyn interprets these directives is needed - so it's not simply a matter of agreeing on or the other.

Realistically though, is there a *single* Nuget package that contains CSX and DLLs at the same time? what is the use case? 
Personally, I'd rather get something tangible implemented, and see what is the feedback on that.

**Comment by adamralph** [comment]
@filipw please see my previous comment which crossed yours. I think `#r` for assemblies and `#load` for scripts _could_ work. I think I have a slight preference for `#r` doing everything, but I wouldn't opposed to the separate approach.

**Comment by adamralph** [comment]
BTW - I just realised that `#load` is the equivalent of `<Compile Include...>` so there is even stronger symmetry if `#r` does everything wrt NuGet packages.

**Comment by seesharper** [comment]
Wouldn't it make sense then to do the combination like suggested before?

```
#r "nuget:simple-targets-csx, 5.3.0"
#load "simple-targets.csx"
```
We then handle the mixed source/binary scenario and we are being explicit about what we are loading.

If ambiguity becomes a problem, which btw also would be a problem with the `#r` only approach,  it might be the case that we should be writing a library and not a script package. 


https://github.com/dotnet/roslyn/issues/4478
> It is not a goal of scripting to replace the C# language proper. Once you need to organize code into namespaces and classes your script is getting too big. You are actually writing a library.

If there are multiple `utils.csx` files across packages, we could at least support the package prefix syntax suggested before in addition to support loading the `utils.csx`  file "directly"

```
#r "nuget:Foo, 1.0.0"
#r "nuget:Bar, 1.0.0"
#load "Foo/util.csx"
```

I don't think we can cover all edge cases here, but we can pretty easily cover the 95% case

**Comment by adamralph** [comment]
I'm not sure how that is better than:

- `#r` does everything, or
- `#r` references assemblies and `#load` compiles scripts

**Comment by seesharper** [comment]
I believe it describes 
* #r references assemblies and #load compiles scripts

The problem with `#r` does everything is first of all that we don't have a way to load the scripts and secondly we could unintentionally load csx files that should not be loaded. 

IMHO, I think it is better to be explicit about what to load

**Comment by seesharper** [comment]
Basically we reference NuGet packages using `#r nuget:"Foo,1.2.3"` syntax like before and the only thing that is added is the ability to (explicitly) load csx files from the referenced package

**Comment by adamralph** [comment]
It does not describe "#r references assemblies and #load compiles scripts". It describes "#r downloads NuGet packages and references assemblies and #load compiles scripts from within NuGet packages downloaded by a separate #r".

"#r references assemblies and #load compiles scripts" describes:

```csx
#r "nuget:mypackage, 1.0.0" // only references the assemblies, no equivalent - script specific
#r "assemblynameorpath" // equivalent of <Reference>
#load "nuget:mypackage, 1.0.0" // only compiles the scripts, no equivalent - script specific
#load "script.csx"  // equivalent of <Compile Include...>
```

I agree with @filipw that we should simply compile all scripts found in the content files. Current content file packages are built with the assumption that all C# files will be compiled and it should be the same with scripts.

**Comment by seesharper** [comment]
Okay, but if we follow up on what @filipw mentioned that we would probably not see to many "mixed" packages,  could we agree on (middleground)

```
#load "nuget:mypackage, 1.0.0"
```

**Comment by seesharper** [comment]
@filipw Do you know if it somehow possible to add additional script files into script compilation without the `#load` directive? Without trying to modify the syntax tree :)

**Comment by adamralph** [comment]
To recap, the options as I see them are:

### Option 1

```csx
#p "mypackage, 1.0.0" // equivalent of <PackageReference>
#r "assemblynameorpath" // equivalent of <Reference>
#load "script.csx"  // equivalent of <Compile Include...>
```

### Option 2

```csx
#r "nuget:mypackage, 1.0.0" // equivalent of <PackageReference>
#r "assemblynameorpath" // equivalent of <Reference>
#load "script.csx"  // equivalent of <Compile Include...>
```

### Option 3

```csx
#r "assemblynameorpath" // equivalent of <Reference>
#r "nuget:mypackage, 1.0.0" // "NuGet enabled #r", no equivalent - script specific
#load "script.csx"  // equivalent of <Compile Include...>
#load "nuget:mypackage, 1.0.0" // "NuGet enabled #load", no equivalent - script specific
```

As I said above, option 1 would be my favoured approach, but assuming we are not backtracking on the current `#r "nuget:mypackage, 1.0.0"`, that leaves options 2 and 3 as possibilities.

I think either can work, and in fact, if `#p` (for lack of a better name) ever did become a thing, then option 3 could lead to an eventual state of:

```csx
#p "mypackage, 1.0.0" // equivalent of <PackageReference>
#r "assemblynameorpath" // equivalent of <Reference>
#r "nuget:mypackage, 1.0.0" // "NuGet enabled #r", no equivalent - script specific
#load "script.csx"  // equivalent of <Compile Include...>
#load "nuget:mypackage, 1.0.0" // "NuGet enabled #load", no equivalent - script specific
```

This way, you could choose to get the whole package, or just pick out the assemblies or the scripts. With this in mind, option 3 is probably the better choice.

As I said above, we should respect the NuGet package conventions and insist on the files matching `contentFiles/csx/{TFM}/*.csx`. It may be necessary to write some non-trivial logic to respect the TFM appropriately depending on the current runtime, including how to choose the "best fit" if the same .csx exists in more than one TFM subfolder. I guess we could copy the logic currently used by MSBuild to choose the TFM for .cs content files.

Is this going to be (or has it already been) mentioned to the Roslyn team before implementation?

**Comment by seesharper** [comment]
There is no doubt after having spent the last two days investigating this that option two is by far the easiest  to implement.  If the package contains csx files we add the path to the NuGet package as a search path into the `SourceFileResolver` already provided by Roslyn.  

Instead of trying to negotiate TFM's, could we consider something like ?

```
#r "nuget:simple-targets-csx, 5.3.0"
#load "{TFM}/simple-targets.csx"
```

**Comment by seesharper** [comment]
I've been looking more into how to load scripts from packages and the more I look at it, the more it makes sense to do this explicitly using the `#load` directive.

Imagine that we have a dependency tree like the following inside a single package.

```shell
A.csx  B.csx    
   \   /   \ 		
   C.csx    D.csx  E.csx
              \    /
               F.csx
```



If we want to use `C.csx` , we would be explicit about it and only load that branch of the dependency tree.

```
#r "nuget:MyPackage, 1.0.0"
#load "C.csx"
```

This means that members from D, E and F will not show up in this case and IMHO I think being explicit adds a level of awareness to the whole experience and to a larger extent follows the principle of least surprise. 

No members start magically to show up in intellisense unless we have loaded the "entry" script.

**Comment by adamralph** [comment]
@seesharper you seemed to be favouring option 3 previously. Leaving the difficulty of implementation aside, is that still your preferred choice?

**Comment by seesharper** [comment]
@adamralph Yes, everything taken into consideration, option 2 is what I think would serve us best here. That is leaving the technical difficulties aside. I do try in general to avoid letting implementation details influence the API. Sometimes I even write the documentation first :)
Here's what I'm thinking. I'll up a branch for this so we can get a look and feel for it. It's not too much work and should be well worth the time and we take it from there. Does that sound okay with you?

**Comment by tmat** [comment]
The semantics of ```#r``` and ```#load``` directives were designed such that the former adds a metadata reference(s) and the latter adds a script file. These are the primitives the compiler has always worked with. The compiler doesn't know anything about nuget packages -- it only works with metadata and source files. The source of these assets is irrelevant. They can be found on disk, generated in memory, in a nuget package, in a database, on the internet, etc. 

Therefore I would suggest to extend ```#load``` to support nuget packages in the same way ```#r``` is currently extended, that is ```#load "nuget: package-name, package-version"```. 

We have actually considered the scenario of loading scripts from packages a while ago while working on Roslyn scripting design. As @seesharper pointed out, including all csx files from the package is not gonna work well with scripts that ```#load``` other scripts in the package. I'd suggest introducing a convention that ```#load "nuget:package"``` finds a script named ```main.csx``` in the content files of the package and loads that file. This file can in turn ```#load``` any number of other scripts or ```#r``` other packages or assemblies. This enables the scenario where a package contains both scripts and assemblies. To load all of them the user of such package would just ```#load``` the package and the ```main.csx``` script in the package would ```#r``` the package itself (or specific assemblies). 

It could be useful to also allow loading a single script other than ```main.csx``` from given package. To implement that the ```#load``` syntax could be further extended to ```#load "nuget: package-name, package-version/relative-script-path.csx"```. The same can be done for ```#r``` of assemblies if found useful. The question here is what should the path be relative too. I'd say to a TFM directory. The TFM should be determined by the host. The script shouldn't be allowed to pick a different TFM for each ```#load``` as all scripts are compiled into a single class. You can't compile half of the class against one TFM and the other half against a different one. Also I'd recommend validating that the relative path doesn't escape the TFM directory (e.g. ```#load "nuget: package-name, package-version/../relative-script-path.csx"``` should be considered invalid.

Note: I'd discourage from manually concatenating script files -- it's not gonna work. E.g. directives must appear first in a script. 

My 2 cents

**Comment by seesharper** [comment]
Thanks @tmat and @adamralph for valuable input on this.

A package could have the following layout then?

```
- content
  - net46
     - utils
        utils.csx
    main.csx  
  - netstandard2.0
     - utils
        utils.csx
    main.csx  
```

We'll figure out which `main.csx` to load based on the target framework of the host.

@filipw We can even provide support for packing script packages 

```
dotnet script pack
```

**Comment by adamralph** [comment]
Thanks for chiming in @tmat.

I agree that `#load "nuget: package-name, package-version"` is the best option.

> As @seesharper pointed out, including all csx files from the package is not gonna work well with scripts that #load other scripts in the package.

Can you please explain why this is a problem? In my experience, it doesn't matter if multiple files in a `#load` dependency tree point back to the same file. E.g. in https://github.com/adamralph/simple-targets-csx many files `#load Utils.csx` in order for IntelliSense to work in VS Code.

> The question here is what should the path be relative too. I'd say to a TFM directory.

👍 

> The TFM should be determined by the host. The script shouldn't be allowed to pick a different TFM for each #load as all scripts are compiled into a single class.

👍 

@seesharper an example package layout would be:

```
- contentFiles
  - csx               // language
    - net46           // TFM
      - utils
        utils.csx
      main.csx
    - netstandard2.0  // TFM
      - utils
        utils.csx
      main.csx
```

Note that "any" is also a valid TFM for content files.. See the [docs](https://docs.microsoft.com/en-gb/nuget/schema/nuspec#including-content-files) for more info. Unfortunately the legacy docs (for old-style csproj) is at the top of the section, and the current docs (for SDK-style csproj) follows it. It also refers to project.json instead of SDK-style csproj (the docs clearly needs some love).

**Comment by tmat** [comment]
> including all csx files from the package is not gonna work well 
> Can you please explain why this is a problem?

It would depend on how the scripts in the package are structured. They can be written in a way that loading all of them works. But in general you can get behavior that's not quite expected:
- The order of ```#load``` might matter. Automatically including all files doesn't allow for ordering specification.
- A package might provide multiple scripts with conflicting definitions, expecting the consumer to ```#load``` just one (kind of like different TFMs but based on some other key). If we imported all scripts by default you'd get confusing errors for ```#load```ing such package.

Perhaps we could amend the ```main.csx``` convention such that if ```main.csx``` is not present we ```#load``` all scripts below given TFM subdirectory.

**Comment by adamralph** [comment]
> - The order of #load might matter. Automatically including all files doesn't allow for ordering specification.

👍 good point. I get it now. When executing a script, the `#load`'s happen in a deterministic order.

> - A package might provide multiple scripts with conflicting definitions, expecting the consumer to #load just one (kind of like different TFMs but based on some other key). If we imported all scripts by default you'd get confusing errors for #loading such package.

Is there a use case for a package which such conflicting definitions? I'd expect a package to be a unit of reference for `#load` as it is for `#r`. I think insisting on a `main.csx` and only loading that is reasonable. IIRC this is how NPM and nodejs work. They insist on an `index.js` and load that as the entry point.

**Comment by seesharper** [comment]
@tmat @adamralph 
> Perhaps we could amend the main.csx convention such that if main.csx is not present we #load all scripts below given TFM subdirectory.

What if we only require `main.csx` if there are more that one csx file at the root level. By root level I mean directly under the TFM directory. For instance the file might be named `build.csx` and this file loads other scripts located in subfolders.  If the `build.csx` in the only file at the root level, we can treat it as `main.csx`.

**Comment by adamralph** [comment]
@seesharper that sounds reasonable to me.

**Comment by tmat** [comment]
@seesharper Is the proposal: a single script in root, otherwise a script in root called ```main.csx```, otherwise error?

I'm wondering if it would be better to check for a script in root called ```main.csx``` first and if there is none ```#load``` all scripts in the order they are specified in nuspec (which is also deterministic, although less obvious than explicitly listed ```#load```s in ```main.csx```).

The latter supports scenario where the package has a set of helper scripts that have no side-effecting top-level code so order doesn't matter.
Having preference for ```main.csx``` would give the option to explicitly control all ```#load```s if needed. If not needed then it's extra overhead to write it.

**Comment by seesharper** [comment]
Yes, @tmat . That was the general idea, but I actually think your suggestion is better since it would probably cover the 90% case without `main.csx`. Could we do a combination, `main.csx` or single root file. If not either, load all scripts in their nuspec declaration order? Or would that be to much ? :)

**Comment by adamralph** [comment]
Incidentally, I've just released https://www.nuget.org/packages/simple-targets-csx/6.0.0 which has it's csx files in `contentFiles/csx/any`.

**Comment by seesharper** [comment]
@adamralph Do you mind if we use `simple-targets` as an example in the documentation for `dotnet-script`

**Comment by adamralph** [comment]
@seesharper no, not at all. 😃

**Comment by seesharper** [comment]
Closing this since we now have basic support for script packages. We can take further discussion in another issue when needed 👍
