### ISSUE TITLE
Only write out the exception message by default

### ISSUE THREAD

**Issue by adamralph** [filipw/dotnet-script#165]
I've also [proposed this for csi.exe](https://github.com/dotnet/roslyn/pull/23018).

**Comment by atifaziz** [comment]
This is [already the case](https://github.com/filipw/dotnet-script/blob/0.15.0/src/Dotnet.Script/Program.cs#L35-L39) unless you specify the debug flag:

```c#
                // Be verbose (stack trace) in debug mode otherwise brief
                var error = args.Any(arg => arg == DebugFlagShort
                                         || arg == DebugFlagLong)
                          ? e.ToString()
                          : e.GetBaseException().Message;
```

**Comment by adamralph** [comment]
@atifaziz when I run dotnet-script with no arguments, I get this:

![image](https://user-images.githubusercontent.com/677704/32446127-c8cd2ce6-c2ff-11e7-8e6a-017b68e3aca7.png)

It looks like the last line is produced by the code you mention, and in fact it is the inner exception, but something else must be printing out the message and stack trace for the outer exception before that happens.

The fact that the code mentioned above is picking out the inner exception message `The system cannot find the file specified`, because it's using `GetBaseException()`, seems wrong. The exception message which should be shown is the outer exception: `Target "build" failed.`

**Comment by atifaziz** [comment]
> something else must be printing out the message and stack trace for the outer exception.

Yep, looks like [that's coming from `ScriptRunner`](https://github.com/filipw/dotnet-script/blob/0.15.0/src/Dotnet.Script.Core/ScriptRunner.cs#L44-L50):

```c#
            if (scriptState.Exception != null)
            {
                Logger.Log("Script execution resulted in an exception.");
                Logger.Log(scriptState.Exception.Message);
                Logger.Log(scriptState.Exception.StackTrace);
                throw scriptState.Exception;
            }
```

I'll let @filipw comment on that piece since he wrote it.

> The exception message which should be shown is the outer exception: `Target "build" failed.`

That's debatable. The inner exception is generally the root cause and more helpful. Consider run-time invocation via reflection. It always throws `TargetInvocationException` with a general message reading, “Exception has been thrown by the target of an invocation.”

The reason the full exception message along with the stack trace is dumped when debug mode is flagged via `-d` or `--debug` is precisely for times when you care about all the gory details.

**Comment by filipw** [comment]
as I commented in the other issue already, the exception is useful because it contains the line number by default.
whether we should cut down the stack trace, that's another discussion - that would probably make sense

**Comment by adamralph** [comment]
👍 withdrawing this. I'll see how https://github.com/dotnet/roslyn/pull/23029 pans out and then I'll come back.

But regardless, this is still writing out the wrong exception message: https://github.com/filipw/dotnet-script/blob/4a59cd89180a0625e8e66e89b1cb62308a40ded9/src/Dotnet.Script/Program.cs#L39 (also a separate discussion).
