### ISSUE TITLE
Align inherited assemblies with Omnisharp

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#181]
@filipw  There is an issue with how we bring in inherited assemblies in `Dotnet.Script` compared to how we do it in OmniSharp. In OmniSharp (.net core scripts) we only bring in `microsoft.codeanalysis.*` and ` system.valuetuple` where as in Dotnet.Script we also bring in everything from `system*` and `mscorlib`.

This is a problem since we could very easily encounter the situation where the script runs fine, but OmniSharp is unable to provide metadata for the additional inherited assemblies that we brought in in the runner. 

The other problem that I am seeing (example below) is that there is quite often a conflict between the inherited assemblies and the assemblies resolved from the script dependency context. That is what is causing the trouble in the example below. 

My suggestion is that we ONLY bring in `microsoft.codeanalysis.*`  as inherited assemblies and everything else is pulled from the script dependency context. 

I've made this change locally and all test are still green in addition to that we also handle the case described below. 

I also noticed a slight perf improvement probably since we bring in fewer dependencies. 

Script to reproduce

```
#! "netcoreapp2.0"


#r "nuget: Microsoft.CodeAnalysis.Scripting, 2.4.0"
#r "nuget: NetStandard.Library, 2.0.0"

List<string> list = new List<string>();
list.FirstOrDefault();
```

> Note: The fact that we bring in `Microsoft.CodeAnalysis.Scripting` is here is just a coincidence and happend to be the case that caused the error to occur. It was an attempt to solve #162 

Error

```
C:\Github\scriptdemo\test.csx(8,1): error CS1705: Assembly 'System.Linq.Queryable' with identity 'System.Linq.Queryable, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Linq.Expressions' with identity 'System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by filipw** [comment]
> My suggestion is that we ONLY bring in microsoft.codeanalysis.* as inherited assemblies and everything else is pulled from the script dependency context.

The reason why it was done like that is that the original idea was to align with CSI, which [brings in a bunch of DLLs](https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Interactive/csi/csi.rsp) by default. In fact they somehow do that for CoreCLR too [see here](https://github.com/dotnet/roslyn/blob/master/src/Interactive/csi/csi.coreclr.rsp)

But we can get rid of that for now to "reset" us back to a clean slate and only think about reintroducing it once we are sure what we want to do (rather than the yolo approach of importing all `System*`). In fact I believe it was removed from OmniSharp as it was causing problems already.
