### ISSUE TITLE
[question] What about VB scripting?

### ISSUE THREAD

**Issue by maximpashuk** [filipw/dotnet-script#247]
I found a package on nuget:

https://www.nuget.org/packages/Microsoft.CodeAnalysis.Scripting/

Description says that Roslyn can also support scripting for VB language.
Any plans on this project to support VB scripting in future?

I know that F# compiler not based on Roslyn so it is very hard to support F# scripting (also project like Fake already exists), but VB is supported.

For newbies in programming VB scripting may be a good start point I think.

**Comment by filipw** [comment]
The description is misleading. This is a shared package that was indeed intended to be used by both C# and VB. 

However, Roslyn scripting support for VB has been put on hold. There was a beta package as part of Roslyn 1.0.0-beta, but afterwards it was never released. 
You can still see traces of it in the [Roslyn source code](https://github.com/dotnet/roslyn/tree/master/src/Scripting/VisualBasic). We even build a prototype of VB support in the scriptcs project but it was abandoned.

It will probably come at some point in the future, but, like I said, AFAIK no one is working on it on the Roslyn side at the moment, so even if it happens, it will take a long time. I will close this issue for now, because there is nothing for us to do here.

**Comment by maximpashuk** [comment]
thank for an answer

**Comment by TomasHubelbauer** [comment]
Just want to chip in here and say this would be cool to have. Not that I write VB .NET every day or anything, but it has language support for XML syntax literals with expression interpolation and this is a really handy feature when you need to produce a fragment of XML where you just need to interpolate some data in.

```xml
~$ dotnet script > file.xml
> <root>
>   <currentDirectory><%= Directory.GetCurrentDirectory() %></currentDirectory>
> </root>
```

Being able to run something like this would be nice :-) But from you comment I get that this is an undertaking so I am completely happy with *some point in the future* if ever, really. Just highlighting a cool use case.
