### ISSUE TITLE
Load external script from URL in directive

### ISSUE THREAD

**Issue by Gorea235** [filipw/dotnet-script#316]
Currently, you can run script from URL in the command line, but the load directive only works with local scripts and ones on nuget. Would it be possible to allow using the load directive from an URL? As an example:

```csharp
#load "https://goo.gl/5eUvu6"

Console.WriteLine(RemoteTest());
```

**Comment by filipw** [comment]
This is not supported by design. We used to support it in the early, early days, but it was removed. 
The main rationale is that we'd like to stay - syntax-wise - compatible with the official Roslyn C# scripting, and such a heavily interpreted `#load` is no longer C# script but a de facto C# script-based DSL, because that feature is not natively supported by Roslyn compiler. So in other words, we want to stay within the boundaries of the official "language spec" of C# scripting.

Now, you might say - "but you already interpret nuget directives there, and that's also not supported by the Roslyn compiler out of box!" - this is true, but that feature has been discussed with the Roslyn team, the syntax has been aligned, and it is on the long term roadmap for Roslyn compiler itself, so dotnet-script is basically giving you a glimpse of the future functionality of the Roslyn compiler.

The reason why running a script from URL is supported is because it is an *outside* feature from the perspective of the script. That is, it's just a convenient way to init the runner, and it doesn't impact the script at the syntactic level like `#load "{url}"` would.

I hope the explanation makes sense.

As a workaround you could package your script as a [script package](https://github.com/filipw/dotnet-script#script-packages), publish to nuget and use from there using `#load "nuget:..."`.

**Comment by Gorea235** [comment]
That seems fair, thanks for clearing it up
