### ISSUE TITLE
Cross compile to .NET Core 3.0

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#413]
We should start cross compiling to .NET Core 3.0.
Certain C# 8 features (ranges, async streams) are only available there. We also want to be compatible when 3.0 RTMs.

I think we can handle this with one global tool package, but this needs to be checked.

**Comment by TomasHubelbauer** [comment]
Is this a reason why `System.Text.Json` is inaccessible for me even through I have the preview SDK for .NET Core 3 installed?

I also noticed that when I switch from `netcoreapp2.0` to `netcoreapp3.0` in `omnisharp.json`, everything in VS Code basically starts erroring out - but this is probably an OmniSharp issue completely outside of dotnet-script, correct?

**Comment by seesharper** [comment]
@TomasHubelbauer We have just started looking into .Net Core 3.0 so this is not something that is supported yet. There is a twofold story to supporting .Net Core 3.0. First of all, `dotnet-script` needs to ship as a `netcoreapp3.0` app so that it knows how to execute these scripts. Then there is the OmniSharp side that needs to be updated to handle metadata references from a .Net Core 3 app.  OmniSharp uses the `Dotnet.Script.DependencyModel` library for that. This library ships with the C# extension and is not tied to the installation of `dotnet-script` you have on your machine. 

So we are working with getting the dependency model to work with .Net Core 3. Once we have that ready, we can update both `dotnet-script` itself and the OmniSharp bits.

**Comment by filipw** [comment]
this is done
