### ISSUE TITLE
Unable to use C# 8 using statements

### ISSUE THREAD

**Issue by dasMulli** [filipw/dotnet-script#611]
Not sure if this belongs here as a matter of compiler configuration or if this is an issue with roslyn...

However, I am unable to compile a simple `.csx` with the latest dotnet-script using using statements. I have run into this when trying to convert a simple console app using only C# 9 top-level statements in Program.cs to a .csx script.

The following script only works without using `using` or `await using`:
```cs
using System.IO;
using System.Text;

var data = Encoding.UTF8.GetBytes("test\n");
await using var file = File.OpenWrite("test.txt");
await file.WriteAsync(data, 0, data.Length);
await file.FlushAsync();
file.Close();
```

```sh
C:\repos\script-using-repro>dotnet tool update -g dotnet-script
Tool 'dotnet-script' was reinstalled with the latest stable version (version '1.0.1').

C:\repos\script-using-repro>dotnet script test.csx
C:\repos\script-using-repro\test.csx(5,7): error CS1519: Invalid token 'using' in class, record, struct, or interface member declaration
C:\repos\script-using-repro\test.csx(5,17): error CS1002: ; expected
C:\repos\script-using-repro\test.csx(5,17): error CS0103: The name 'file' does not exist in the current context
C:\repos\script-using-repro\test.csx(6,7): error CS0103: The name 'file' does not exist in the current context
C:\repos\script-using-repro\test.csx(7,7): error CS0103: The name 'file' does not exist in the current context
C:\repos\script-using-repro\test.csx(8,1): error CS0103: The name 'file' does not exist in the current context
```

**Comment by filipw** [comment]
Unfortunately this is a limitation of Roslyn. You cannot use using statements as global script variables.

Top level CSX variables are compiled into fields of the script class at runtime.
This typically is opaque to the user and acts as "global variable". However, it doesn't work with using declarations, because you cannot have a using on a field. 

On the other hand, this works:

```
var data = Encoding.UTF8.GetBytes("test\n");

{
    await using var file = File.OpenWrite("test.txt");
    await file.WriteAsync(data, 0, data.Length);
    await file.FlushAsync();
    file.Close();
}
```

since you have an artifical scope and `file` is now really a local not a field on the script class.

PS. `System.IO` and `System.Text` are automatically available in the script context 🙂

**Comment by dasMulli** [comment]
Thanks for the info and workaround!
