### ISSUE TITLE
Unable to install dotnet-script

### ISSUE THREAD

**Issue by drewburlingame** [filipw/dotnet-script#621]
I get this error running `dotnet tool install -g dotnet-script`

![image](https://user-images.githubusercontent.com/103345/117380325-586f0200-aed1-11eb-864e-ab5853dae206.png)

It looks like dotnet.myget.com was retired and MS is directing to use Azure Artifacts
https://docs.microsoft.com/en-us/answers/questions/337663/invalid-certificate-for-mygetorg.html

**Comment by filipw** [comment]
Thanks for the issue, but this is not a dotnet-script problem, but a dotnet CLI problem. You would see the same error with any other dotnet tool e.g. `dotnet tool install -g dotnet-outdated`.

Check your NuGet config files (https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) it sounds like your global NuGet config has the Roslyn myget API feed configured. 
Since `dotnet tool` command scans all of them, it throws an error. You should remove the retired feeds from there.

**Comment by drewburlingame** [comment]
Wow, you're right.  Apologies for the bother and thank you for the generous response.
