### ISSUE TITLE
Is it possible to use dotnet-script without installing the SDK (using runtime only) ?

### ISSUE THREAD

**Issue by uffebjorklund** [filipw/dotnet-script#653]
I think I know the answer, but I had to ask :D

**Comment by filipw** [comment]
yes you can publish a self contained executable using `dotnet script publish {script name}.csx`. You can find all the options here https://github.com/filipw/dotnet-script#creating-dlls-or-exes-from-a-csx-file

It creates a self contained dotnet executable which can be executed from the command line as any executable. Because of that it will be about ~80MB in size.

**Comment by uffebjorklund** [comment]
@filipw That is a good option, but will unfortunately not work in our case.
Basically we have a low code solution (kind of [node-red](https://nodered.org/) but for .NET) where users build flows in a drag n drop UI connecting modules to build logic...
Most modules are purpose built, but we have a few code modules such as `Python`, `IronPython` and `C#`. Since `dotnet-script` offer so much more with `nuget packages` etc we thought it would be cool to add `dotnet-script` as a module as well. Would provide huge flexibility for use-cases were we do not have a module ready.

Since the code often run on small gateways (or other edge devices) we try to keep the runtime as small as possible and loading one or more `dotnet-scripts` with 80mb each will not be an option today.

Anyway, thanks for the quick answer. Really love dotnet-script and use it for a lot of other stuff almost daily
